field_150350_a=AIR
field_188423_x=GLOWING
field_70161_v=posZ
field_70163_u=posY
field_70165_t=posX
field_70177_z=rotationYaw
field_72338_b=minY
field_75837_b=y
field_75838_c=z
field_75839_a=x
func_174813_aQ=getEntityBoundingBox
func_175149_v=isSpectator
func_176223_P=getDefaultState
func_177227_a=getPropertyKeys
func_184609_a=swingArm
func_184614_ca=getHeldItemMainhand
func_184812_l_=isCreative
func_190926_b=isEmpty
func_70089_S=isEntityAlive
func_70092_e=getDistanceSq
func_70635_at=getEntitySenses
func_70644_a=isPotionActive
func_70661_as=getNavigator
func_70671_ap=getLookHelper
func_70681_au=getRNG
func_75246_d=updateTask
func_75492_a=tryMoveToXYZ
func_75497_a=tryMoveToEntityLiving
func_75505_d=getPath
func_75522_a=canSee
func_75651_a=setLookPositionWithEntity
func_75870_c=getFinalPathPoint
func_76128_c=floor
func_76142_g=wrapDegrees
